import { montserrat } from "./fonts";
import { LenisProvider } from "./(providers)/lenisprovider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <LenisProvider >
        <body className={`bg-customGray ${montserrat.className}`}>{children}</body>
      </LenisProvider>
    </html>
  );
}
